-- 用戶表
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    email VARCHAR(255)
);

-- 用戶角色表
CREATE TABLE user_roles (
    user_id BIGINT,
    roles VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 產品表
CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    price DOUBLE PRECISION,
    stock INTEGER
);

-- 購物車項目表
CREATE TABLE cart_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    product_id BIGINT,
    quantity INTEGER,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

-- 訂單表
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    total_amount DECIMAL(19,2),
    status VARCHAR(50),
    payment_status VARCHAR(50),
    created_at TIMESTAMP,
    payment_method VARCHAR(50),
    payment_transaction_id VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 訂單項目表
CREATE TABLE order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT,
    product_id BIGINT,
    quantity INTEGER,
    price DECIMAL(19,2),
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
); 